modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="broken_mind_weapons"
version="1.0.0"
displayName="Broken Mind Weapons"
credits="Clemardo, Lagartino, Maxsteelbro, MCreator"
displayURL="https://mcreator.net"
description='''
Adds weapons with special abilitys
'''

[[dependencies.broken_mind_weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




